FROM node:lts
RUN mkdir -p ./ui
WORKDIR /ui

COPY ./public ./public
COPY ./src ./src
COPY ./config ./config

COPY ./package*.json ./tsconfig.json ./custom.d.ts ./
RUN npm install

EXPOSE 3000
CMD npm start

